---
A. Anwhar Raajhaa: 4893
A. Arunmozhithevan: 4849
A.P. Jithender Reddy: 380
A.T. Nana Patil: 4370
Abhijit Mukherjee: 4581
Abhishek Banerjee: 4843
Abhishek Singh: 4742
Abu Hasem Khan Choudhury: 4212
Adhikari Deepak (Dev): 4847
Adhir Ranjan Chowdhury: 97
Ajay Misra Teni: 4696
Ajay Nishad: 4715
Ajay Tamta: 4651
Akshay Yadav: 4779
Alok Sanjar: 4703
Amarinder Singh: 2660
Anandrao Adsul: 8
Anant Gangaram Geete: 136
Anant Kumar Hegde: 3688
Ananth Kumar: 20
Anbumani Ramadoss: 4648
Anil Shirole: 4746
Anirudhan Sampath: 3777
Anju Bala: 4724
Anoop Mishra: 4637
Anshul Verma: 4675
Anto Antony: 4571
Anupam Hazra: 4870
Anupriya Singh Patel: 4662
Anurag Singh Thakur: 4249
Aparupa Poddar (Afrin Ali): 4844
Arjun Charan Sethi: 411
Arjun Ram Meghwal: 4399
Arjunlal Meena: 4755
Arka Keshari Deo: 4797
Arpita Ghosh: 4864
Arun Kumar: 208
Arvind Sawant: 4713
Asaduddin Owaisi: 4091
Ashok Gajapathi Raju Pusapati: 4760
Ashok Kumar Doharey: 4697
Ashok Mahadeorao Nete: 4748
Ashok Shankarrao Chavan: 2999
Ashwini Kumar: 4649
Ashwini Kumar Choubey: 4650
Asrarul Haque Mohammad: 4460
Azmeera Seetaram Naik: 4874
B. S. Yeddyurappa: 4599
B. Senguttuvan: 4902
B. Sreeramulu: 4762
B.N. Chandrappa: 4846
B.V. Nayak: 4790
Babul Supriya Baral (Babul Supriyo): 4704
Badaruddoza Khan: 4824
Badruddin Ajmal: 4436
Bahadur Singh: 436
Baijayant Jay Panda: 4422
Balabhadra Majhi: 4796
Balka Suman: 4805
Bandaru Dattatreya: 105
Banshilal Mahto: 4882
Bhagat Singh Koshyari: 4639
Bhagirath Prasad: 4613
Bhagwant Mann: 4635
Bhagwanth Khuba: 4632
Bhairon Prasad Mishra: 4626
Bhanu Pratap Singh Verma: 3824
Bharat Singh: 4695
Bharatendra Singh: 4723
Bharatiben Dhirubhai Shiyal: 4693
Bhartruhari Mahtab: 225
Bhavana Pundlikrao Gawali Patil: 135
Bheemrao B. Patil: 4756
Bhola Singh: 4605
Bhuwan Chandra Khanduri: 196
Bidyut Baran Mahato: 4705
Bijoy Chandra Barman: 4853
Bijoya Chakravarty: 69
Biren Singh Engti: 2084
Birendra Kumar Chaudhary: 4736
Bishnu Pada Ray: 371
Bodhsingh Bhagat: 4652
Boora Narsaiah Goud: 4803
Brij Bhushan Sharan Singh: 438
Butta Renuka: 4681
C. Gopalakrishnan: 4860
C. L. Ruala: 4353
C. Mahendran: 4842
C. R. Patil: 4452
C.N. Jayadevan: 4827
C.R. Choudhary: 4636
C.S. Puttaraju: 4821
Chand Nath: 4631
Chandra Prakash Joshi: 4671
Chandrakant Bhaurao Khaire: 189
Chandu Barne Shrirang: 4781
Chandu Lal Sahu: 4362
Charanjeet Singh Rori: 4732
Chauhan Devusinh Jesingbhai: 4858
Chavda Vinod Lakhamashi: 4741
Chhedi Paswan: 3361
Chhotelal: 4859
Chintaman Navasha Wanga: 519
Chintamani Malviya: 4646
Chirag Kumar Paswan: 4777
Choudhury Mohan Jatua: 4492
Chudasama Rajeshbhai Naranbhai: 4865
D.K. Suresh: 4585
D.V. Sadananda Gowda: 3979
Daddan Mishra: 4592
Dalpat Singh Paraste: 291
Darshana Vikram Jardosh: 4451
Dasrath Tirkey: 4908
Deepender Singh Hooda: 4207
Devendra Singh @ Bhole Singh: 4664
Devji Patel: 4411
Dhananjay Bhimrao Mahadik: 4767
Dharam Vira Gandhi: 4676
Dharambir: 4647
Dharmendra Kumar: 4595
Dharmendra Yadav: 4206
Dhruva Narayana Rangaswamy: 4342
Dileepsingh Bhuria: 2692
Dilip Kumar Mansukhlal Gandhi: 128
Dilip Patel: 4887
Dimple Yadav: 4580
Dinesh Kashyap: 4576
Dinesh Trivedi: 4487
Dr Bhola Singh: 4475
Dushyant Chautala: 4624
Dushyant Singh: 4005
E. Ahamed: 10
E. T. Mohammed Basheer: 4561
Faggan Singh Kulaste: 207
Fatepara Devajibhai Govindbhai: 4863
Feroze Varun Gandhi: 4277
G. Hari: 4869
Gajanan Chandrakant Kirtikar: 4922
Gajendrasingh Shekhawat: 4670
Ganesh Singh: 3986
Giriraj Singh: 4641
Godam Nagesh: 4804
Godse Hemant Tukaram: 4682
Gokaraju Ganga Raju: 4610
Gopal Chinayya Shetty: 4661
Gourav Gogoi: 4788
Gowdar Mallikarjunappa Siddeswara: 3977
H.D. Devegowda: 3960
Hansraj Gangaram Ahir: 3640
Hari Manjhi: 4474
Hari Om Pandey: 4672
Haribhai Parthibhai Chaudhary: 76
Harinarayan Rajbhar: 4891
Harinder Singh Khalsa: 3704
Hariom Singh Rathore: 4655
Harish Chandra Alias Harish Dwivedi: 4633
Harish Chandra Meena: 4640
Harishchandra Deoram Chavan: 3991
Harsh Vardhan: 4776
Harsimrat Kaur Badal: 4433
Heena Vaijaykumar Gavit: 4787
Hema Malini: 4619
Hemendra Chandra Singh: 4811
Hukamdeo Narayan Yadav: 528
Hukum Singh: 4593
Idris Ali: 4848
Inderjit Singh Rao: 3904
Innocent: 4886
J. Jayavardhan: 4873
J. Jeyasingh Thiyagaraj Natterjee: 4876
J.C. Divakar Reddi: 4700
Jadhav Prataprao Ganpatrao: 4373
Jagdambika Pal: 4295
Jai Prakash Narayan Yadav: 4095
Janak Ram: 4719
Janardan Mishra: 4728
Janardan Singh Sigriwal: 4638
Jasvantsinh Sumanbhai Bhabhor: 4857
Jayadev Galla: 4770
Jayant Sinha: 4768
Jayshreeben Kanubhai Patel: 4442
Jhina Hikaka: 4812
Jitendra Choudhury: 4826
Jitendra Singh: 4718
Joice George: 4686
Jose K. Mani: 4566
Jual @ Juel Oram: 279
Jugal Kishore: 4720
Jyoti Dhurve: 4522
Jyotiraditya Madhavrao Scindia: 3958
K. Ashok Kumar: 4850
K. C. Venugopal: 4567
K. Gopal: 4829
K. Kamaraj: 4836
K. Maragatham: 4835
K. Parasuraman: 4885
K.C. Patel: 4818
K.H. Muniyappa: 261
K.N. Ramachandran: 4889
K.R.P.  Prabakaran: 4840
K.V. Thomas: 3209
Kadiyam Srihari: 4801
Kakoli Ghosh Dastidar: 4489
Kalikesh Narayan Singh Deo: 4419
Kalraj Mishra: 4721
Kalvakuntla Kavitha: 4802
Kalyan Banerjee: 4498
Kamakhya Prasad Tasa: 4739
Kamal Nath: 175
Kamalbhan Singh Marabi: 4690
Kambhampati Hari Babu: 4743
Kamla Devi Patle: 4358
Kamlesh Paswan: 4303
Kanwar Singh Tanwar: 4607
Kapil Krishna Thakur: 4907
Kapil Moreshwar Patil: 4658
Karadi Sanganna Amarappa: 4744
Kariya Munda: 259
Kaushal Kishore: 4710
Kaushalendra Kumar: 4467
Keshav Prasad Maurya: 4594
Kesineni Srinivas: 4701
Kiren Rijiju: 3972
Kirit Premjibhai Solanki: 4444
Kirit Somaiya: 467
Kirron Anupam Kher: 4775
Kirti (Jha) Azad: 25
Kirti Vardhan Singh: 3926
Konakalla Narayana Rao: 4527
Konda Vishweshwar Reddy: 4800
Kothapalli Geetha: 4679
Krishan Pal: 4629
Krishna Pratap K.P.: 4673
Krishna Raj: 4694
Kristappa Nimmala: 4529
Krupal Balaji Tumane: 4734
Kulamani Samal: 4820
Kundariya Mohanbhai Kalyanjibhai: 4692
Kunwer Sarvesh Kumar: 4778
Ladu Kishore Swain: 4814
Lakhan Lal Sahu: 4689
Lal Krishna Advani: 9
Lallu Singh: 4752
Lalubhai Babubhai Patel: 4364
Laxman Giluwa: 140
Laxmi Narayan Yadav: 4611
Liladharbhai Khodaji Vaghela: 4914
M. B. Rajesh: 4562
M. Chandrakasi: 4856
M. I. Shanavas: 4559
M. K. Raghavan: 4560
M. Udhaya Kumar: 4909
M. Vasanthi: 4839
M. Veerappa Moily: 4343
Maganti Venkateswara Rao (Babu): 3942
Mahboob Ali Kaiser: 4612
Maheish Girri: 4608
Mahendra Nath Pandey: 4917
Mahesh Sharma: 4642
Mala Rajya Laxmi Shah: 4582
Malla Reddy: 4773
Mallikarjun Kharge: 4315
Malyadri Sriram: 4769
Mamtaz Sanghamita: 4899
Maneka Gandhi: 129
Manohar Untwal: 4910
Manoj Rajoria: 4667
Manoj Sinha: 463
Manoj Tiwari: 4606
Manshankar Ninama: 4880
Mansukhbhai D. Vasava: 501
Mausam Noor: 4483
Md. Salim: 4190
Meenakashi Lekhi: 4717
Mehbooba Mufti: 4111
Mekapati Rajamohan Reddy: 3394
Mriganka Mahato: 4881
Mukesh Rajput: 4666
Mulayam Singh Yadav: 530
Munisamy Thambidurai: 3205
Murali Mohan Maganti: 4699
Murli Manohar Joshi: 172
Muttamsetti Srinivasa Rao (Avanthi): 4740
Muzaffar Hussain Baig: 4806
N.K.Premachandran: 3754
Naba Kumar Sarania (Hira): 4774
Nagendra Kumar Pradhan: 4813
Nagendra Singh: 4738
Nalin Kumar Kateel: 4316
Nanabhau Falgunrao Patole: 4895
Nandkumar Singh Chouhan (Nandu Bhaiya): 82
Naramalli Sivaprasad: 4531
Naranbhai Kachhadia: 4448
Narendra Keshav Sawaikar: 4754
Narendra Modi: 4589
Narendra Singh Tomar: 4507
Natubhai Gomanbhai Patel: 4365
Neelam Sonkar: 4621
Neiphiu Rio: 4897
Nepal Singh: 4602
Nihalchand: 95
Ninong Ering: 4367
Niranjan Jyoti: 4622
Nishikant Dubey: 4324
Nitin Jairam Gadkari: 4923
Nityanand Rai: 4625
Om Birla: 4716
Om Prakash Yadav: 4462
P. C. Mohan: 4321
P. K. Biju: 4563
P. Karunakaran: 4178
P. Kumar: 4546
P. Nagarajan: 4883
P. Radhakrishnan: 341
P. Venugopal: 4532
P.C. Gaddigoudar: 3984
P.K. Sreemathi Teacher: 4906
P.P. Choudhary: 4597
P.P. Mohammed Faizal: 4786
P.R. Senthilnathan: 4838
P.R. Sundaram: 4905
P.V. Midhun Reddy: 4688
Pandula Ravindra Babu: 4884
Pankaj Chowdhary: 3479
Paresh Rawal: 4747
Parvesh Sahib Singh Verma: 4758
Pashupati Nath Singh: 4326
Pinaki Misra: 3724
Ponguleti Srinivasa Reddy: 4683
Poonam Mahajan Alias Poonam Vajendla Rao: 4660
Poonamben Hematbhai Maadam: 4751
Prabhas Kumar Singh: 4807
Prabhatsinh Pratapsinh Chauhan: 4449
Prahlad Singh Patel: 306
Prakash Babanna Hukkeri: 4924
Pralhad Venkatesh Joshi: 3982
Prasanna Kumar Patasani: 299
Prasun Banerjee: 4583
Prathap Simha: 4708
Pratima Mondal: 4871
Prem Das Rai: 4347
Prem Singh Chandumajra: 3667
Priyanka Singh Rawat: 4677
Purno Agitok Sangma: 394
Pushpendra Singh Chandel: 4665
R. Gopalakrishnan: 4831
R. Parthipan: 4837
R. Radhakrishnan: 4894
R. Vanaroja: 4913
R.K. Bharathi Mohan: 4852
R.P. Marutharajaa: 4867
Rabindra Kumar Jena: 4795
Radha Mohan Singh: 451
Radheshyam Biswas: 4808
Raghav Lakhanpal: 4785
Rahul Gandhi: 4074
Rahul Kaswan: 4654
Rahul Ramesh Shewale: 4903
Raj Kumar Saini: 4620
Raj Kumar Singh: 4653
Rajan Baburao Vichare: 4663
Rajeev Shankarrao Satav: 4798
Rajen Gohain: 143
Rajendra Agrawal: 4267
Rajesh Kumar Diwaker: 4609
Rajesh Pandey Urf Guddu: 4698
Rajesh Ranjan @ Pappu Yadav: 554
Rajesh Verma: 510
Rajiv Pratap Rudy: 385
Rajnath Singh: 4268
Raju Shetti: 4397
Rajveer Singh (Raju Bhaiya): 4634
Rajyavardhan Singh Rathore: 4782
Rakesh Singh: 3987
Raksha Nikhil Khadase: 4722
Ram Chandra Paswan: 297
Ram Charitra Nishad: 4617
Ram Kripal Yadav: 3832
Ram Kumar Sharma: 4714
Ram Prasad Sarmah: 4753
Ram Swaroop Sharma: 4763
Ram Tahal Choudhary: 78
Ram Vilas Paswan: 296
Rama Chandra Hansdah: 4825
Rama Devi: 3901
Rama Kishore Singh: 4749
Ramachandran Mullappally: 3085
Ramcharan Bohara: 4656
Ramdas Chandrabhanji Tadas: 4911
Ramen Deka: 4437
Ramesh Bais: 33
Ramesh Bidhuri: 4854
Ramesh Chandappa Jigajinagi: 170
Ramesh Pokhriyal Nishank: 4761
Rameswar Teli: 4745
Rammohan Naidu Kinjarapu: 4771
Ramshankar: 4274
Ramsinhbhai Patalyabhai Rathwa: 364
Ranjeet Ranjan: 4093
Ranjit Singh Brahmpura: 4919
Raosaheb Patil Danve: 316
Rathod Dipsinh Shankarsinh: 4691
Ratna De: 4499
Rattan Lal Kataria: 183
Ravindra Kumar Pandey: 285
Ravindra Kumar Ray: 4668
Ravindra Kushawaha: 4879
Ravindra Vishwanath Gaikwad: 4766
Ravneet Singh: 4429
Rekha Verma: 4918
Renuka Sinha: 4904
Rita Tarai: 4832
Riti Pathak: 4711
Rodmal Nagar: 4702
S. Rajendran: 4890
S. Selvakumara Chinnayan: 4861
S.P. Muddahanumegowda: 4791
S.P.Y. Reddy: 4024
S.R. Vijayakumar: 4830
S.S. Ahluwalia: 4793
Sadashiv Kisan Lokhande: 4733
Sadhu Singh: 4674
Sakuntala Laguri: 4810
Sambasiva Rayapati Rao: 3763
Sandhya Roy: 4898
Sanjay (Bandu) Haribhau Jadhav: 4735
Sanjay Jaiswal: 4455
Sanjay Shamrao Dhotre: 3992
Sanjaykaka Patil: 4680
Sanjeev Kumar Balyan: 4921
Sankar Prasad Datta: 4822
Santokh Singh Chaudhary: 4783
Santosh Ahlawat: 4628
Santosh Kumar: 4792
Santosh Kumar Gangwar: 131
Sanwar Lal Jat: 4707
Sarbananda Sonowal: 4163
Satabdi Roy: 4506
Satish Chandra Dubey: 4862
Satish Kumar: 4603
Satya Pal Singh: 4600
Satyapal Singh: 4630
Saugata Roy: 2554
Saumitra Khan: 4875
Savitri Bai Foole: 4780
Savitri Thakur: 4596
Shailesh Kumar Urph Bulo Mandal: 4794
Shanta Kumar: 418
Sharad Bansode: 4706
Sharad Tripathi: 4712
Shashi Tharoor: 4569
Shatrughan Sinha: 4468
Sher Singh Ghubaya: 4432
Shibu Soren: 2917
Shivaji Adhalrao Patil: 4143
Shobha Karandlaje: 4616
Shrikant Eknath Shinde: 4659
Shrimant Chh. Udyanraje Pratapsinhmaharaj Bhonsle: 4389
Shripad Yesso Naik: 273
Shyama Charan Gupta: 4173
Sidhant Mohapatra: 4425
Siraj Uddin Ajmal: 4817
Sisir Kumar Adhikari: 4502
Sona Ram: 89
Sonia Gandhi: 130
Sreemati Dev Varma (Moon Moon Sen): 4912
Subhash Baheria: 3654
Subhash Patel: 4685
Subhash Ramrao Bhamre: 4678
Subrata Bakshi: 4578
Sudarshan Bhagat: 4329
Sudhir Gupta: 4615
Sudip Bandyopadhyay: 38
Sugata Bose: 4851
Sukender Reddy Gutha: 375
Sukhbir Singh Jaunapuria: 4669
Sultan Ahmed: 4497
Sumedhanand Saraswati: 4709
Sumitra Mahajan: 220
Sunil Baliram Gaikwad: 4643
Sunil Kumar Mondal: 4868
Sunil Kumar Singh: 4750
Supriya Sule: 4392
Suresh Channabasappa Angadi: 3983
Suresh Kodikunnil: 477
Sushil Kumar Singh: 3928
Sushma Swaraj: 3812
Sushmita Dev: 4784
Suvendu Adhikari: 4501
Swami Sachchidanand Hari Sakshi: 3586
T. Radhakrishnan: 4892
T.G. Venkatesh Babu: 4916
Tamradhwaj Sahu: 4614
Tapas Mandal: 4845
Tapas Paul: 4484
Tariq Anwar: 2664
Tariq Hameed Karra: 4819
Tasleem Uddin: 3439
Tathagata Satpathy: 3918
Thangso Baite: 4351
Thokchom Meinya: 4055
Thota Narasimham: 4799
Thupstan Chhewang: 4089
Udasi Shivkumar Chanabasappa: 4340
Uday Pratap Singh: 4516
Udit Raj: 4764
Uma Bharati: 496
Uma Saren: 4900
Upendra Kushwaha: 4645
V. Elumalai: 4841
V. Pannerselvam: 4833
V. Sathyabama: 4901
Varaprasad Rao Velagapalli: 4920
Vasava Parbhubhai Nagarbhai: 4757
Veena Devi: 4684
Vijay Kumar Hansdak: 4866
Vijay Kumar Singh: 4598
Vijay Sampla: 4618
Vijaysinh Shankarrao Mohite Patil: 4789
Vikram Dev Usendi: 4915
Vinayak Bhaurao Raut: 4765
Vincent H Pala: 4352
Vinod Khanna: 197
Vinod Kumar Boinapally: 4084
Vinod Kumar Sonkar: 4623
Virender Kashyap: 4298
Virendra Kumar: 515
Virendra Singh: 3608
Vishnu Dayal Ram: 4731
Vishnu Deo Sai: 389
Vitthalbhai Hansrajbhai Radadiya: 4446
Y.S. Avinash Reddy: 4816
Y.V. Subba Reddy: 4687
Yashwant Singh: 4657
Yellaiah Nandi: 2649
Yogi Adityanath: 7
